

export const statuses = {
  LOADING_BOOKS : "LOADING_BOOKS",
  LOAD_BOOKS_SUCCESS : "LOAD_BOOKS_SUCCESS",
  LOAD_BOOKS_FAILED : "LOAD_BOOKS_FAILED",
  BOOKS_NOT_LOADED : "BOOKS_NOT_LOADED",

  SAVING_NEW_BOOK : "SAVING_NEW_BOOK",
  SAVE_NEW_BOOK_SUCCESS : "SAVE_NEW_BOOK_SUCCESS",
  SAVE_NEW_BOOK_FAILED : "SAVE_NEW_BOOK_FAILED",
  SAVE_NEW_BOOK_NOT_LOADED: "SAVE_NEW_BOOK_NOT_LOADED", 
}