

export const types = {
  LOADING_BOOKS : "LOADING_BOOKS",
  LOAD_BOOKS_SUCCESS : "LOAD_BOOKS_SUCCESS",
  LOAD_BOOKS_FAILED : "LOAD_BOOKS_FAILED",
  LOAD_BOOKS_INIT_VALUE : "LOAD_BOOKS_INIT_VALUE",

  SAVING_NEW_BOOK : "SAVING_NEW_BOOK",
  SAVE_NEW_BOOK_SUCCESS : "SAVE_NEW_BOOK_SUCCESS",
  SAVE_NEW_BOOK_FAILED : "SAVE_NEW_BOOK_FAILED",
  SAVE_NEW_BOOK_INIT_VALUE: "SAVE_NEW_BOOK_INIT_VALUE", 

  EDITING_BOOK : "EDITING_BOOK",
  EDIT_BOOK_SUCCESS : "EDIT_BOOK_SUCCESS",
  EDIT_BOOK_FAILED : "EDIT_BOOK_FAILED",
  EDIT_BOOK_INIT_VALUE : "EDIT_BOOK_INIT_VALUE",

  DELETING_BOOK : "DELETING_BOOK",
  DELETE_BOOK_SUCCESS : "DELETE_BOOK_SUCCESS",
  DELETE_BOOK_FAILED : "DELETE_BOOK_FAILED",
  DELETE_BOOK_INIT_VALUE : "DELETE_BOOK_INIT_VALUE"

}